// src/app/models/student.model.ts
export interface Student {
  id: number;
  name: string;
  surName: string;
  rollNo: string;
  schoolClass?: SchoolClass | null;
  age: number;
  gender: 'MALE' | 'FEMALE';
  guardianName?: string;
  phone?: string;
  image_path?: string;
  fees: Fee[];
  status: string;
  admissionDate: string;
  attendance: Attendance[];
  dateOfBirth?: string;
  fatherName?: string;
  surname?: string;
  imagePath?: string;
  whatsapp?: string;
  classId?: number;
  address?: string;
  schoolName?: string;
  parentProfession?: string;
  preferredTime?: string;
}

// src/app/models/school-class.model.ts
export interface SchoolClass {
  studentCount: number;
  timing: string;
  division: string;
  id?: number;
  name: string;
  teacher?: Teacher[];
  subject?: Subject[];
  student?: Student[];
}

// src/app/models/teacher.model.ts
export interface Teacher {
  id?: number;
  fullName: string;
  phone?: string;
  subject?: Subject[]; // ✅ make sure this exists and is an array
}

// src/app/models/subject.model.ts
export interface Subject {
  id?: number;
  name: string;
  classes?: SchoolClass[];
  teacher?: Teacher[];
}

// src/app/models/attendance.model.ts
export interface Attendance {
  id: number;
  studentId: number;
  studentName: string;
  student: Student;
  className: string;
  attendanceDate: string; // YYYY-MM-DD
  attendanceStatus: 'PRESENT' | 'ABSENT';
  remark: string;
}

// src/app/models/fee.model.ts
export interface Fee {
  id: number;
  studentId: number;
  month: string;
  year: number;
  status: string;
  paymentDate: Date;
  dueDate: Date;
  paymentMode: string;
  recordedBy: string;
  remark: string;
  paidAmount: number;
}

export interface BatchFeeRequest {
  studentIds: number[];
  status: string;
}

export interface FeeResponse {
  studentId: number;
  feeId: number;
  status: string;
}

export interface BatchFeeResponse {
  createdFees: FeeResponse[];
  message: string;
}

export interface FeeDTO {
  month: string;
  amount: number;
  status: string;
}

export interface StudentFeeDTO {
  studentName: string;
  studentClass: string;
  fees: FeeDTO[];
}

export interface ManualData {
  id?: number;                // optional because it's generated by backend
  studentName: string;
  fatherName: string;
  surname: string;
  dob: string;                // can be Date if you want to parse it
  age: number;
  gender: string;
  address: string;
  mobileNo: string;
  residential: string;
  schoolName: string;
  parentsProfession: string;
  preferredTiming: string;
  admissionDate: string;
  teacherName: string;
  schoolClass: string;
  feesDetail: string;
  division: string;
  dataJson?: string;
}
